[package]
name = "tom"
version = "0.1.0"
authors = ["Klaas-Jan Boon <klaas-janboon@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.1"
hmac = "0.10.1"
